In [1]:
import pandas as pd

In [2]:
athletes = pd.read_csv('athletes.csv', low_memory=False)

In [3]:
athletes['deadlift'].mean()

697.0502761808139

In [14]:
athletes[athletes['deadlift']>900].shape

(50, 28)

In [118]:
athletes.head()

,athlete_id,name,region,team,affiliate,gender,age,height,weight,fran,...,deadlift,backsq,pullups,eat,train,background,experience,schedule,howlong,retrieved_datetime
0,2554.0,Pj Ablang,South West,Double Edge,Double Edge CrossFit,Male,24.0,70.0,166.0,NaN,...,400.0,305.0,NaN,NaN,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|I r...,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|,NaN
1,3517.0,Derek Abdella,NaN,NaN,NaN,Male,42.0,70.0,190.0,NaN,...,NaN,NaN,NaN,NaN,I have a coach who determines my programming|I...,I played youth or high school level sports|,I began CrossFit with a coach (e.g. at an affi...,I do multiple workouts in a day 2x a week|,4+ years|,NaN
2,4691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5164.0,Abo Brandon,Southern California,LAX CrossFit,LAX CrossFit,Male,40.0,67.0,NaN,211.0,...,375.0,325.0,25.0,I eat 1-3 full cheat meals per week|,I workout mostly at a CrossFit Affiliate|I hav...,I played youth or high school level sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|,4+ years|,NaN
4,5286.0,Bryce Abbey,NaN,NaN,NaN,Male,32.0,65.0,149.0,206.0,...,NaN,325.0,50.0,I eat quality foods but don't measure the amount|,I workout mostly at a CrossFit Affiliate|I inc...,I played college sports|,I began CrossFit by trying it alone (without a...,I usually only do 1 workout a day|I strictly s...,1-2 years|,NaN

In [64]:
athletes.background.value_counts()[:15]

I played youth or high school level sports|                                                                                              36262
I have no athletic background besides CrossFit|                                                                                          13975
I played youth or high school level sports|I regularly play recreational sports|                                                         13957
I played youth or high school level sports|I played college sports|                                                                       9202
I played college sports|                                                                                                                  7580
I played youth or high school level sports|I played college sports|I regularly play recreational sports|                                  5644
I regularly play recreational sports|                                                                                                     4771
I played college sports|I regularly play recreational sports|                                                                             1455
I played professional sports|                                                                                                             1366
Decline to answer|                                                                                                                         966
I have no athletic background besides CrossFit|I played youth or high school level sports|                                                 708
I have no athletic background besides CrossFit|I regularly play recreational sports|                                                       582
I played youth or high school level sports|I played college sports|I played professional sports|                                           524
I played youth or high school level sports|I played college sports|I played professional sports|I regularly play recreational sports|      394
I played college sports|I played professional sports|                                                                                      382
Name: background, dtype: int64

In [65]:
athletes = athletes.dropna(subset=['background'])

In [66]:
profs = athletes[athletes['background'].str.contains('I played professional sports')]
profs_idx = profs.index
athletes['background'].loc[profs_idx.values] = 'I played professional sports'

In [67]:
coll = athletes[athletes['background'].str.contains('I played college sports')]
coll_idx = coll.index
athletes['background'].loc[coll_idx.values] = 'I played college sports'

In [68]:
schools = athletes[athletes['background'].str.contains('I played youth or high school level sports')]
schools_idx = schools.index
athletes['background'].loc[schools_idx.values] = 'I played youth or high school level sports'

In [70]:
recr = athletes[athletes['background'].str.contains('I regularly play recreational sports')]
recr_idx = recr.index
athletes['background'].loc[recr_idx.values] = 'I regularly play recreational sports'

In [72]:
nobg = athletes[athletes['background'].str.contains('I have no athletic background besides CrossFit')]
nobg_idx = nobg.index
athletes['background'].loc[nobg_idx.values] = 'No athletic background'

In [77]:
semi_pro = athletes[athletes['background'].isin(['I played college sports', 'I played professional sports'])]
semi_pro_idx = semi_pro.index
athletes['background'].loc[semi_pro_idx.values] = 'Pro or college sports'

In [79]:
some_sport = athletes[athletes['background'].isin(['I played youth or high school level sports', 'I regularly play recreational sports'])]
some_sport_idx = some_sport.index
athletes['background'].loc[some_sport_idx.values] = 'Some sport (youth, school, recreational)'

In [81]:
new_df = athletes[athletes['background'].isin(['No athletic background', 'Pro or college sports', 'Some sport (youth, school, recreational)'])]

In [82]:
new_df.background.value_counts()

Some sport (youth, school, recreational)    56446
Pro or college sports                       27548
No athletic background                      13985
Name: background, dtype: int64

In [86]:
new_df.to_csv('athletes_background.csv', index=False)

In [119]:
athletes = pd.read_csv('athletes_background.csv')

In [120]:
athletes.gender.value_counts()

Male      64061
Female    33911
--            7
Name: gender, dtype: int64

In [121]:
athletes = athletes[athletes['gender'].isin(['Male','Female'])]

In [122]:
athletes.gender.value_counts()

Male      64061
Female    33911
Name: gender, dtype: int64

In [123]:
athletes.howlong.value_counts()

1-2 years|                                                                        32402
2-4 years|                                                                        23964
6-12 months|                                                                      18235
Less than 6 months|                                                               12671
4+ years|                                                                          7570
6-12 months|1-2 years|                                                              445
1-2 years|2-4 years|                                                                429
Less than 6 months|1-2 years|                                                       354
Decline to answer|                                                                  161
2-4 years|4+ years|                                                                 131
Less than 6 months|6-12 months|                                                      86
6-12 months|2-4 years|                                                               82
Less than 6 months|2-4 years|                                                        47
1-2 years|4+ years|                                                                  20
Less than 6 months|6-12 months|1-2 years|                                            14
6-12 months|4+ years|                                                                 9
Less than 6 months|Decline to answer|                                                 8
6-12 months|1-2 years|2-4 years|                                                      8
Less than 6 months|4+ years|                                                          7
Less than 6 months|6-12 months|1-2 years|2-4 years|4+ years|Decline to answer|        6
Less than 6 months|6-12 months|1-2 years|2-4 years|4+ years|                          5
1-2 years|Decline to answer|                                                          5
2-4 years|Decline to answer|                                                          5
6-12 months|Decline to answer|                                                        3
6-12 months|1-2 years|2-4 years|4+ years|                                             3
Less than 6 months|1-2 years|2-4 years|                                               2
6-12 months|1-2 years|Decline to answer|                                              2
Less than 6 months|6-12 months|1-2 years|2-4 years|                                   2
1-2 years|2-4 years|4+ years|                                                         2
|                                                                                     1
Name: howlong, dtype: int64

In [126]:
athletes = athletes[['name', 'gender', 'age', 'height', 'weight', 'candj', 'snatch', 'deadlift', 'backsq', 'pullups', 'eat', 'background', 'schedule','howlong' ]]

In [127]:
athletes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97972 entries, 0 to 97978
Data columns (total 14 columns):
name          97972 non-null object
gender        97972 non-null object
age           97972 non-null float64
height        88141 non-null float64
weight        84930 non-null float64
candj         65812 non-null float64
snatch        62240 non-null float64
deadlift      72003 non-null float64
backsq        69418 non-null float64
pullups       34995 non-null float64
eat           86592 non-null object
background    97972 non-null object
schedule      90233 non-null object
howlong       96679 non-null object
dtypes: float64(8), object(6)
memory usage: 11.2+ MB

In [128]:
athletes.to_csv('athletes_edited.csv', index=False)

In [147]:
athletes=pd.read_csv('athletes_edited.csv')

In [148]:
athletes = athletes.dropna(how='any')

In [149]:
athletes.head()

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,eat,background,schedule,howlong
5,Anthony Abeel,Male,21.0,72.0,175.0,0.0,0.0,0.0,0.0,0.0,I eat quality foods but don't measure the amou...,No athletic background,I do multiple workouts in a day 3+ times a wee...,2-4 years|
7,Mike Abgarian,Male,31.0,65.0,150.0,290.0,225.0,465.0,405.0,81.0,I eat quality foods but don't measure the amou...,Pro or college sports,I do multiple workouts in a day 3+ times a week|,2-4 years|
8,Kipp Abbott,Male,43.0,71.0,185.0,0.0,0.0,0.0,0.0,0.0,I eat quality foods but don't measure the amount|,No athletic background,I usually only do 1 workout a day|I typically ...,2-4 years|
9,Ignacio Abascal,Male,23.0,72.0,165.0,220.0,187.0,419.0,0.0,55.0,I eat quality foods but don't measure the amount|,Pro or college sports,I usually only do 1 workout a day|I do multipl...,6-12 months|
13,Erik Acevedo,Male,30.0,71.0,200.0,235.0,175.0,385.0,315.0,35.0,I eat whatever is convenient|,Pro or college sports,I do multiple workouts in a day 1x a week|I ty...,1-2 years|

In [150]:
athletes = athletes.query('candj != 0.0 and snatch != 0.0 and deadlift != 0.0 and backsq != 0.0 and pullups != 0.0')

In [151]:
athletes.shape

(23257, 14)

In [153]:
athletes.head()

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,eat,background,schedule,howlong
7,Mike Abgarian,Male,31.0,65.0,150.0,290.0,225.0,465.0,405.0,81.0,I eat quality foods but don't measure the amou...,Pro or college sports,I do multiple workouts in a day 3+ times a week|,2-4 years|
13,Erik Acevedo,Male,30.0,71.0,200.0,235.0,175.0,385.0,315.0,35.0,I eat whatever is convenient|,Pro or college sports,I do multiple workouts in a day 1x a week|I ty...,1-2 years|
14,Richard Ablett,Male,28.0,70.0,176.0,187.0,134.0,335.0,254.0,27.0,I eat 1-3 full cheat meals per week|,No athletic background,I do multiple workouts in a day 1x a week|,2-4 years|
15,Joji Abasolo,Male,39.0,66.0,158.0,185.0,135.0,385.0,285.0,31.0,I eat strict Paleo|I eat quality foods but don...,"Some sport (youth, school, recreational)",I do multiple workouts in a day 3+ times a week|,1-2 years|
16,Joe Abruzzo,Male,35.0,68.0,225.0,285.0,205.0,440.0,405.0,24.0,I eat quality foods but don't measure the amount|,"Some sport (youth, school, recreational)",I typically rest 4 or more days per month|,2-4 years|

In [154]:
athletes.to_csv('athletes_allinfo.csv', index=False)

In [155]:
athletes = pd.read_csv('athletes_allinfo.csv')

In [158]:
paleo = athletes[athletes['eat'].str.contains('I eat strict Paleo')]
paleo_idx = paleo.index
athletes['eat'].loc[paleo_idx.values] = 'Paleo'

C:\Users\lobov\Anaconda3\envs\dand\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [160]:
evr = athletes[athletes['eat'].str.contains('I eat whatever is convenient')]
evr_idx = evr.index
athletes['eat'].loc[evr_idx.values] = 'Everything'

In [162]:
qual = athletes[athletes['eat'].str.contains("I eat quality foods but don't measure the amount")]
qual_idx = qual.index
athletes['eat'].loc[qual_idx.values] = 'Quality Food'

In [164]:
wei = athletes[athletes['eat'].str.contains("I weigh and measure my food")]
wei_idx = wei.index
athletes['eat'].loc[wei_idx.values] = 'Weigh and measure food'

In [166]:
evr = athletes[athletes['eat'].str.contains("I eat 1-3 full cheat meals per week")]
evr_idx = evr.index
athletes['eat'].loc[evr_idx.values] = 'Everything'

In [168]:
athletes = athletes[athletes['eat'].isin(['Quality Food', 'Everything', 'Paleo', 'Weigh and measure food'])]

In [169]:
athletes.eat.value_counts()

Quality Food              14433
Everything                 5180
Paleo                      2060
Weigh and measure food     1344
Name: eat, dtype: int64

In [170]:
athletes.head()

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,eat,background,schedule,howlong
0,Mike Abgarian,Male,31.0,65.0,150.0,290.0,225.0,465.0,405.0,81.0,Quality Food,Pro or college sports,I do multiple workouts in a day 3+ times a week|,2-4 years|
1,Erik Acevedo,Male,30.0,71.0,200.0,235.0,175.0,385.0,315.0,35.0,Everything,Pro or college sports,I do multiple workouts in a day 1x a week|I ty...,1-2 years|
2,Richard Ablett,Male,28.0,70.0,176.0,187.0,134.0,335.0,254.0,27.0,Everything,No athletic background,I do multiple workouts in a day 1x a week|,2-4 years|
3,Joji Abasolo,Male,39.0,66.0,158.0,185.0,135.0,385.0,285.0,31.0,Paleo,"Some sport (youth, school, recreational)",I do multiple workouts in a day 3+ times a week|,1-2 years|
4,Joe Abruzzo,Male,35.0,68.0,225.0,285.0,205.0,440.0,405.0,24.0,Quality Food,"Some sport (youth, school, recreational)",I typically rest 4 or more days per month|,2-4 years|

In [171]:
athletes.to_csv('athletes_allinfo.csv', index=False)

In [184]:
athletes = pd.read_csv('athletes_allinfo.csv')

In [185]:
one = athletes[athletes['schedule'].str.contains("I usually only do 1 workout a day")]
one_idx = one.index
athletes['schedule'].loc[one_idx.values] = 'One workout a day'

In [186]:
mult = athletes[athletes['schedule'].str.contains("I do multiple workouts in a day 3")]
mult_idx = mult.index
athletes['schedule'].loc[mult_idx.values] = 'Multiple workouts in a day'

In [189]:
mult1 = athletes[athletes['schedule'].str.contains("I do multiple workouts in a day")]
mult1_idx = mult1.index
athletes['schedule'].loc[mult1_idx.values] = 'One or multiple'

In [191]:
athletes = athletes[athletes['schedule'].isin(['One workout a day', 'Multiple workouts in a day', 'One or multiple'])]

In [192]:
athletes.shape

(21349, 14)

In [193]:
athletes.to_csv('athletes_allinfo.csv', index=False)

In [205]:
athletes = pd.read_csv('athletes_allinfo.csv')

In [206]:
athletes['age'] = athletes['age'].astype(int)
athletes['height'] = athletes['height'].astype(int)
athletes['weight'] = athletes['weight'].astype(int)
athletes['candj'] = athletes['candj'].astype(int)
athletes['snatch'] = athletes['snatch'].astype(int)
athletes['deadlift'] = athletes['deadlift'].astype(int)
athletes['backsq'] = athletes['backsq'].astype(int)
athletes['pullups'] = athletes['pullups'].astype(int)

In [207]:
athletes

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,eat,background,schedule,howlong
0,Mike Abgarian,Male,31,65,150,290,225,465,405,81,Quality Food,Pro or college sports,Multiple workouts in a day,2-4 years|
1,Erik Acevedo,Male,30,71,200,235,175,385,315,35,Everything,Pro or college sports,One or multiple,1-2 years|
2,Richard Ablett,Male,28,70,176,187,134,335,254,27,Everything,No athletic background,One or multiple,2-4 years|
3,Joji Abasolo,Male,39,66,158,185,135,385,285,31,Paleo,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years|
4,Jerry Abadom,Male,44,72,214,265,198,551,485,37,Paleo,Pro or college sports,One or multiple,1-2 years|
5,Brigham Abbott,Male,36,71,199,267,212,485,390,33,Quality Food,Pro or college sports,Multiple workouts in a day,1-2 years|
6,Jason Ackerman,Male,36,64,155,245,180,415,385,50,Paleo,Pro or college sports,One or multiple,4+ years|
7,Brian Abreu,Male,31,75,235,225,185,425,275,15,Everything,No athletic background,One workout a day,2-4 years|
8,Matthew Adamcheck,Male,26,71,235,315,240,515,415,40,Everything,No athletic background,Multiple workouts in a day,4+ years|
9,Bill Adams,Male,44,69,168,245,185,435,405,34,Quality Food,"Some sport (youth, school, recreational)",One workout a day,4+ years|
10,Justin Adams,Male,24,68,180,315,240,475,405,80,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,2-4 years|
11,Andy Adams,Male,26,70,197,325,250,500,425,30,Quality Food,"Some sport (youth, school, recreational)",One workout a day,4+ years|
12,Daniel Adamson,Male,31,67,150,230,175,410,330,42,Quality Food,Pro or college sports,One workout a day,2-4 years|
13,Bryan Acosta,Male,28,71,205,325,260,455,405,50,Everything,"Some sport (youth, school, recreational)",Multiple workouts in a day,2-4 years|
14,Landon Adams,Male,34,69,185,275,215,530,450,51,Quality Food,Pro or college sports,Multiple workouts in a day,4+ years|
15,Steven Lee Adams,Male,37,72,210,285,205,525,425,49,Quality Food,Pro or college sports,One or multiple,4+ years|
16,Micah Adams,Male,37,72,180,198,110,375,265,25,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years|
17,Lorin Adams,Male,27,73,210,320,250,485,415,48,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years|
18,jaime acuna,Male,23,71,175,305,255,505,445,96,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years|
19,Nicholas Acord,Male,30,68,210,255,175,455,365,32,Quality Food,Pro or college sports,One workout a day,2-4 years|
20,Carlos Acosta,Male,41,67,178,235,185,455,375,47,Everything,Pro or college sports,One or multiple,2-4 years|
21,Joe Adams,Male,31,71,160,225,175,385,315,35,Weigh and measure food,"Some sport (youth, school, recreational)",One or multiple,4+ years|
22,Gavin Adcock,Male,45,67,165,165,121,353,243,23,Quality Food,"Some sport (youth, school, recreational)",One workout a day,2-4 years|
23,a.j Adam,Male,28,71,175,165,105,285,185,10,Quality Food,"Some sport (youth, school, recreational)",One workout a day,1-2 years|
24,John Adams,Male,30,72,220,225,165,425,325,16,Quality Food,No athletic background,One workout a day,1-2 years|2-4 years|
25,Craig Adams,Male,44,71,201,254,172,441,364,40,Quality Food,"Some sport (youth, school, recreational)",One workout a day,2-4 years|
26,Dan Adams,Male,36,74,203,231,198,375,276,44,Quality Food,"Some sport (youth, school, recreational)",One workout a day,1-2 years|
27,David Ackland,Male,31,72,182,225,165,415,305,42,Everything,Pro or college sports,One workout a day,2-4 years|
28,Jan-Ronald Agay,Male,39,66,153,225,165,360,300,35,Quality Food,"Some sport (youth, school, recreational)",One workout a day,2-4 years|
29,John Aguilar,Male,25,71,180,260,225,405,320,30,Everything,No athletic background,One or multiple,2-4 years|
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21319,Keith Moore,Male,45,75,245,205,185,330,275,7,Quality Food,Pro or college sports,Multiple workouts in a day,1-2 years|
21320,Verdant Nolan,Male,36,71,185,95,95,95,225,14,Quality Food,"Some sport (youth, school, recreational)",One workout a day,6-12 months|
21321,Abdulaziz Hayati,Male,24,69,70,132,88,260,154,10,Paleo,No athletic background,One workout a day,6-12 months|
21322,Jonathan Ison,Male,37,69,250,175,165,435,365,5,Quality Food,"Some sport (youth, school, recreational)",One workout a day,6-12 months|
21323,Conor Gross,Male,18,72,150,130,115,255,190,21,Everything,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years|
21324,Amariah Hash,Male,41,72,217,150,125,225,235,6,Weigh and measure food,"Some sport (youth, school, recreational)",One workout a day,Less than 6 months|
21325,Luz MuÃ±oz,Female,18,63,112,145,115,235,185,50,Everything,No athletic background,Multiple workouts in a day,6-12 months|
21326,Natalie Bourke,Female,23,60,121,95,77,220,154,10,Paleo,Pro or college sports,Multiple workouts in a day,6-12 months|
21327,Ashley Williams,Female,29,64,143,140,95,265,215,12,Weigh and measure food,"Some sport (youth, school, recreational)",One workout a day,1-2 years|
21328,Alex Smith,Female,22,63,128,130,90,205,170,10,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,Less than 6 months|
21329,Alisha Aufai,Female,25,71,205,140,105,275,220,3,Quality Food,"Some sport (youth, school, recreational)",One workout a day,6-12 months|
21330,Kariny Castelo Cavalcante Mota,Female,21,63,106,70,50,150,125,4,Everything,"Some sport (youth, school, recreational)",One workout a day,Less than 6 months|
21331,Mauricio Cardona Lozano,Male,33,72,183,125,135,305,275,15,Quality Food,Pro or college sports,One workout a day,Less than 6 months|
21332,Michel Menjikoff,Male,32,65,157,150,121,331,231,20,Everything,No athletic background,One workout a day,6-12 months|
21333,Garrett Gomes,Male,35,75,215,225,180,435,350,30,Paleo,"Some sport (youth, school, recreational)",One workout a day,2-4 years|
21334,Geoffrey Chrisman,Male,30,66,161,170,135,325,235,16,Quality Food,"Some sport (youth, school, recreational)",One workout a day,1-2 years|
21335,Joseph Bowers,Male,27,67,172,145,125,265,205,3,Paleo,No athletic background,One workout a day,Less than 6 months|
21336,Chandler Smith,Male,21,67,180,300,240,525,415,56,Everything,Pro or college sports,Multiple workouts in a day,4+ years|
21337,Joe Taylor,Male,24,69,190,209,154,386,309,20,Everything,Pro or college sports,One workout a day,Less than 6 months|
21338,Stacey Quarles,Male,47,75,255,225,205,505,505,13,Quality Food,Pro or college sports,Multiple workouts in a day,1-2 years|2-4 years|
21339,Bobby Schudler,Male,43,71,169,175,125,315,225,25,Quality Food,Pro or college sports,One workout a day,6-12 months|
21340,Jerry Patterson,Male,27,67,155,125,65,135,175,12,Everything,"Some sport (youth, school, recreational)",One workout a day,Less than 6 months|
21341,Josh Meyer,Male,33,71,198,190,125,315,255,23,Quality Food,"Some sport (youth, school, recreational)",Multiple workouts in a day,2-4 years|
21342,Darrel Hilton,Male,37,70,214,198,165,485,287,27,Quality Food,Pro or college sports,One workout a day,1-2 years|
21343,Doug Thompson,Male,47,70,170,125,115,255,195,11,Quality Food,"Some sport (youth, school, recreational)",One workout a day,Less than 6 months|
21344,Carley Feil,Female,20,67,140,112,84,209,180,7,Quality Food,"Some sport (youth, school, recreational)",One workout a day,Less than 6 months|
21345,Jeffrey Mckibben,Male,25,67,175,135,115,275,225,40,Quality Food,No athletic background,One workout a day,1-2 years|
21346,Barbara Puzanovova,Female,19,66,145,125,90,200,145,3,Everything,No athletic background,One workout a day,Less than 6 months|
21347,Allen Griffin,Male,33,74,250,295,205,515,510,8,Everything,"Some sport (youth, school, recreational)",One workout a day,2-4 years|
21348,Gabriela Madia,Female,25,64,126,110,88,243,176,12,Quality Food,Pro or college sports,One workout a day,Less than 6 months|

In [208]:
athletes.howlong.value_counts()

2-4 years|                                                                        7371
1-2 years|                                                                        6928
4+ years|                                                                         3158
6-12 months|                                                                      2356
Less than 6 months|                                                               1002
1-2 years|2-4 years|                                                               163
6-12 months|1-2 years|                                                             126
2-4 years|4+ years|                                                                 68
Less than 6 months|1-2 years|                                                       64
Decline to answer|                                                                  24
6-12 months|2-4 years|                                                              22
Less than 6 months|6-12 months|                                                     18
Less than 6 months|2-4 years|                                                       16
1-2 years|4+ years|                                                                  6
Less than 6 months|6-12 months|1-2 years|2-4 years|4+ years|Decline to answer|       4
Less than 6 months|4+ years|                                                         4
Less than 6 months|6-12 months|1-2 years|                                            3
1-2 years|2-4 years|4+ years|                                                        2
2-4 years|Decline to answer|                                                         2
Less than 6 months|1-2 years|2-4 years|                                              2
6-12 months|1-2 years|2-4 years|                                                     2
Less than 6 months|Decline to answer|                                                2
1-2 years|Decline to answer|                                                         1
Less than 6 months|6-12 months|1-2 years|2-4 years|4+ years|                         1
|                                                                                    1
6-12 months|4+ years|                                                                1
6-12 months|1-2 years|Decline to answer|                                             1
6-12 months|1-2 years|2-4 years|4+ years|                                            1
Name: howlong, dtype: int64

In [231]:
howl1 = athletes[athletes['howlong'] == "4+ years|"]
howl1_idx = howl1.index
athletes['howlong'].loc[howl1_idx.values] = '4+ years'

In [233]:
athletes = athletes[athletes['howlong'].isin(['Less than 1 year', '1-2 years', '2-4 years', '4+ years'])]

In [234]:
athletes.howlong.value_counts()

2-4 years           7371
1-2 years           7091
Less than 1 year    3505
4+ years            3226
Name: howlong, dtype: int64

In [254]:
athletes.to_csv('athletes_allinfo.csv', index=False)
athletes = pd.read_csv('athletes_allinfo.csv')

In [255]:
athletes.shape

(21193, 13)

In [256]:
athletes.head()

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,background,schedule,howlong
0,Mike Abgarian,Male,31,65,150,290,225,465,405,81,Pro or college sports,Multiple workouts in a day,2-4 years
1,Erik Acevedo,Male,30,71,200,235,175,385,315,35,Pro or college sports,One or multiple,1-2 years
2,Richard Ablett,Male,28,70,176,187,134,335,254,27,No athletic background,One or multiple,2-4 years
3,Joji Abasolo,Male,39,66,158,185,135,385,285,31,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years
4,Jerry Abadom,Male,44,72,214,265,198,551,485,37,Pro or college sports,One or multiple,1-2 years

In [248]:
atl1 = pd.read_csv('athletes.csv', low_memory=False)

In [253]:
athletes = athletes.drop(columns=['eat'])

In [249]:
athletes.shape

(21193, 14)

In [250]:
names = athletes['name']

In [251]:
names.nunique()

20843

In [252]:
names.shape

(21193,)

In [262]:
athletes = pd.read_csv('athletes_allinfo.csv')

In [273]:
athletes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21193 entries, 0 to 21192
Data columns (total 13 columns):
name          21193 non-null object
gender        21193 non-null category
age           21193 non-null int64
height        21193 non-null int64
weight        21193 non-null int64
candj         21193 non-null int64
snatch        21193 non-null int64
deadlift      21193 non-null int64
backsq        21193 non-null int64
pullups       21193 non-null int64
background    21193 non-null category
schedule      21193 non-null category
howlong       21193 non-null category
dtypes: category(4), int64(8), object(1)
memory usage: 1.5+ MB

In [264]:
genders = ['Male', 'Female']
vclasses = pd.api.types.CategoricalDtype(ordered=False, categories=genders)
athletes['gender'] = athletes['gender'].astype(vclasses)

In [265]:
athletes.background.value_counts()

Some sport (youth, school, recreational)    12345
Pro or college sports                        6511
No athletic background                       2337
Name: background, dtype: int64

In [266]:
backgrounds = ['Some sport (youth, school, recreational)', 'Pro or college sports', 'No athletic background']
vclasses = pd.api.types.CategoricalDtype(ordered=True, categories=backgrounds)
athletes['background'] = athletes['background'].astype(vclasses)

In [268]:
athletes.schedule.value_counts()

One workout a day             12401
Multiple workouts in a day     5070
One or multiple                3722
Name: schedule, dtype: int64

In [269]:
schedules = ['One workout a day', 'Multiple workouts in a day', 'One or multiple']
vclasses = pd.api.types.CategoricalDtype(ordered=True, categories=schedules)
athletes['schedule'] = athletes['schedule'].astype(vclasses)

In [271]:
athletes.howlong.value_counts()

2-4 years           7371
1-2 years           7091
Less than 1 year    3505
4+ years            3226
Name: howlong, dtype: int64

In [272]:
howlongs = ['2-4 years', '1-2 years', 'Less than 1 year', '4+ years']
vclasses = pd.api.types.CategoricalDtype(ordered=True, categories=howlongs)
athletes['howlong'] = athletes['howlong'].astype(vclasses)

In [71]:
athletes.to_csv('athletes_complete.csv', index=False)

In [69]:
athletes = pd.read_csv('athletes_complete.csv')

In [70]:
athletes = athletes[athletes['deadlift'] > 10]
athletes = athletes[athletes['snatch'] > 10]
athletes = athletes[athletes['candj'] > 10]
athletes = athletes[athletes['backsq'] > 10]
athletes = athletes[athletes['pullups'] > 0]

In [16]:
athletes = athletes[athletes['deadlift'] < 900]

In [20]:
athletes = athletes[athletes['snatch'] < 390]

In [29]:
athletes = athletes[athletes['candj'] < 450]

In [34]:
athletes = athletes[athletes['backsq'] < 900]

In [33]:
athletes[athletes['backsq'] > 900]

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,background,schedule,howlong
5006,Mario Ramirez,Male,22,68,191,285,225,455,4010,21,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years
5568,Brandon Winnie,Male,37,72,185,265,205,490,3450,55,Pro or college sports,One or multiple,4+ years
14773,Abigail Carnes,Female,25,67,145,125,85,195,1651,8,Pro or college sports,One workout a day,1-2 years

In [52]:
athletes.pullups.describe()

count    2.115500e+04
mean     1.015902e+05
std      1.476466e+07
min     -5.000000e+00
25%      2.000000e+01
50%      3.000000e+01
75%      4.000000e+01
max      2.147484e+09
Name: pullups, dtype: float64

In [64]:
athletes = athletes[athletes['pullups'] < 100]

In [5]:
athletes.head()

,name,gender,age,height,weight,candj,snatch,deadlift,backsq,pullups,background,schedule,howlong
0,Mike Abgarian,Male,31,65,150,290,225,465,405,81,Pro or college sports,Multiple workouts in a day,2-4 years
1,Erik Acevedo,Male,30,71,200,235,175,385,315,35,Pro or college sports,One or multiple,1-2 years
2,Richard Ablett,Male,28,70,176,187,134,335,254,27,No athletic background,One or multiple,2-4 years
3,Joji Abasolo,Male,39,66,158,185,135,385,285,31,"Some sport (youth, school, recreational)",Multiple workouts in a day,1-2 years
4,Jerry Abadom,Male,44,72,214,265,198,551,485,37,Pro or college sports,One or multiple,1-2 years

In [49]:
athletes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21155 entries, 0 to 21192
Data columns (total 13 columns):
name          21155 non-null object
gender        21155 non-null object
age           21155 non-null int64
height        21155 non-null int64
weight        21155 non-null int64
candj         21155 non-null int64
snatch        21155 non-null int64
deadlift      21155 non-null int64
backsq        21155 non-null int64
pullups       21155 non-null int64
background    21155 non-null object
schedule      21155 non-null object
howlong       21155 non-null object
dtypes: int64(8), object(5)
memory usage: 2.3+ MB